const express = require('express');
const router = express.Router();
const staffAuth = require('../middlewares/staffAuthMiddleware');
const checkPermission = require('../middlewares/rbacMiddleware');
const upload = require('../middlewares/uploadMiddleware');
const csvUpload = require('../middlewares/csvUploadMiddleware');
const roomUpload = require('../middlewares/roomUploadMiddleware');
const brandingUpload = require('../middlewares/brandingUploadMiddleware');
const adminController = require('../controllers/adminController');

router.use(staffAuth);

router.get('/dashboard', checkPermission('dashboard', 'view'), adminController.getDashboard);
router.get('/system/health', checkPermission('system', 'view'), adminController.getSystemHealth);
router.get('/users', checkPermission('users', 'view'), adminController.getUsers);
router.post('/users', checkPermission('users', 'create'), adminController.createUser);
router.put('/users/:id', checkPermission('users', 'edit'), adminController.updateUser);
router.delete('/users/:id', checkPermission('users', 'delete'), adminController.deleteUser);
router.get('/roles', checkPermission('roles', 'view'), adminController.getRoles);
router.put('/roles/:id', checkPermission('roles', 'edit'), adminController.updateRoleDetails);
router.put('/roles/:id/permissions', checkPermission('roles', 'edit'), adminController.updateRolePermissions);
router.get('/settings/payment-gateways', checkPermission('settings', 'view'), adminController.getPaymentGateways);
router.put('/settings/payment-gateways/:name', checkPermission('settings', 'edit'), adminController.updatePaymentGateway);
router.get('/settings', checkPermission('settings', 'view'), adminController.getSettings);
router.put('/settings', checkPermission('settings', 'edit'), adminController.updateSettings);
router.post('/settings/logo', checkPermission('settings', 'edit'), brandingUpload.single('logo'), adminController.uploadHotelLogo);
router.post('/settings/internal-logo', checkPermission('settings', 'edit'), brandingUpload.single('logo'), adminController.uploadInternalLogo);
router.get('/audit-logs', checkPermission('audit-logs', 'view'), adminController.getAuditLogs);
router.get('/financial/dashboard', checkPermission('dashboard', 'view'), adminController.getFinancialDashboard);
router.get('/backup', checkPermission('system', 'view'), adminController.getBackups);
router.post('/backup/create', checkPermission('system', 'create'), adminController.createBackup);
router.post('/backup/:id/restore', checkPermission('system', 'edit'), adminController.restoreBackup);
router.get('/integrations', checkPermission('integrations', 'view'), adminController.getIntegrations);
router.post('/integrations/booking-com/sync', checkPermission('integrations', 'edit'), adminController.syncBookingCom);
router.put('/integrations/booking-com', checkPermission('integrations', 'edit'), adminController.updateBookingComIntegration);
router.post('/integrations/booking-com/test-connection', checkPermission('integrations', 'edit'), adminController.testBookingComConnection);
router.get('/integrations/booking-com/webhook-logs', checkPermission('integrations', 'view'), adminController.getWebhookLogs);
router.post('/integrations/booking-com/webhook-logs/:id/retry', checkPermission('integrations', 'edit'), adminController.retryWebhookLog);
router.post('/integrations/booking-com/commission-reconciliation', checkPermission('integrations', 'edit'), csvUpload.single('statement'), adminController.uploadCommissionStatement);
router.put('/integrations/key-card-system', checkPermission('integrations', 'edit'), adminController.updateKeyCardSystem);
router.put('/room-types/:id/booking-com-mapping', checkPermission('integrations', 'edit'), adminController.updateRoomTypeBookingComMapping);
router.post('/integrations/booking-com/ari-push', checkPermission('integrations', 'edit'), adminController.pushAri);
router.get('/room-types', checkPermission('settings', 'view'), adminController.getRoomTypes);
router.post('/room-types', checkPermission('settings', 'create'), adminController.createRoomType);
router.delete('/room-types/:id', checkPermission('settings', 'delete'), adminController.deleteRoomType);
router.put('/room-types/:id', checkPermission('settings', 'edit'), adminController.updateRoomType);
router.post('/room-types/:id/photo', checkPermission('settings', 'edit'), upload.single('photo'), adminController.uploadRoomTypePhoto);
router.get('/rooms', checkPermission('settings', 'view'), adminController.getRooms);
router.post('/rooms', checkPermission('settings', 'create'), adminController.createRoom);
router.put('/rooms/:id', checkPermission('settings', 'edit'), adminController.updateRoom);
router.post('/rooms/:id/photo', checkPermission('settings', 'edit'), roomUpload.single('photo'), adminController.uploadRoomPhoto);
router.delete('/rooms/:id', checkPermission('settings', 'delete'), adminController.deleteRoom);

module.exports = router;
